from collections.abc import Awaitable, Buffer, Iterable, Iterator, Mapping, Sequence
from typing import overload

__version__: str
MAX_BATCH_ITEMS: int
MAX_BATCH_VALUE_BYTES: int
MAX_KEY_LIST_LIMIT: int

class _JsonObject(Mapping[str, object]):
    def __getitem__(self, key: str) -> object: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def to_builtin(self) -> dict[str, object]: ...

class _JsonArray(Sequence[object]):
    @overload
    def __getitem__(self, index: int) -> object: ...
    @overload
    def __getitem__(self, index: slice) -> tuple[object, ...]: ...
    def __len__(self) -> int: ...
    def to_builtin(self) -> list[object]: ...

class VaultletError(Exception): ...
class ConfigurationError(VaultletError): ...
class SerializationError(VaultletError): ...
class InvalidKeyError(VaultletError): ...
class IntegrityError(VaultletError): ...
class UnsupportedFormatError(IntegrityError): ...
class StoreLockedError(VaultletError): ...
class BackendError(VaultletError): ...
class ClosedError(VaultletError): ...
class TypeMismatchError(VaultletError): ...

class _NativeMasterKey:
    @staticmethod
    def generate() -> _NativeMasterKey: ...
    @staticmethod
    def from_bytes(value: Buffer) -> _NativeMasterKey: ...
    @staticmethod
    def from_base64(value: str) -> _NativeMasterKey: ...
    def export_bytes(self) -> bytes: ...
    def export_base64(self) -> str: ...

class _NativeStore:
    @property
    def closed(self) -> bool: ...
    def tenant(self, tenant_id: str) -> _NativeTenant: ...
    def rotate_master_key(self, key: _NativeMasterKey) -> Awaitable[None]: ...
    def purge_expired(self) -> Awaitable[int]: ...
    def close(self) -> Awaitable[None]: ...

class _NativeTenant:
    def set(
        self, key: str, value: Buffer, expires_at_ms: int | None
    ) -> Awaitable[None]: ...
    def get(self, key: str) -> Awaitable[bytes | None]: ...
    def set_many(
        self, values: Mapping[str, Buffer], expires_at_ms: int | None
    ) -> Awaitable[None]: ...
    def get_many(self, keys: Iterable[str]) -> Awaitable[dict[str, bytes]]: ...
    def set_json(
        self, key: str, value: object, expires_at_ms: int | None
    ) -> Awaitable[None]: ...
    def get_json(self, key: str) -> Awaitable[object | None]: ...
    def set_many_json(
        self, values: Mapping[str, object], expires_at_ms: int | None
    ) -> Awaitable[None]: ...
    def get_many_json(self, keys: Iterable[str]) -> Awaitable[dict[str, object]]: ...
    def delete(self, key: str) -> Awaitable[bool]: ...
    def delete_many(self, keys: Iterable[str]) -> Awaitable[int]: ...
    def exists(self, key: str) -> Awaitable[bool]: ...
    def metadata(self, key: str) -> Awaitable[tuple[int, int, int | None] | None]: ...
    def keys(
        self, limit: int, cursor: str | None
    ) -> Awaitable[tuple[list[str], bool, str | None]]: ...

def open_store(
    path: str,
    key: _NativeMasterKey,
    cleanup_interval_ms: int,
    engine: str,
) -> Awaitable[_NativeStore]: ...
def open_redis_store(
    endpoint: str,
    namespace: str,
    credentials: tuple[str | None, str | None],
    key: _NativeMasterKey,
    cleanup_interval_ms: int,
    timeouts_ms: tuple[int, int, int],
) -> Awaitable[_NativeStore]: ...
